ip: localhost
port: 1883
trigger_topic: "test/camera/trigger"
image_topic: "test/image/colour_image"
trigger_time_topic: "test/image/trigger_time"
message: null

camera:
  camera_type: opencv

camera_settings:
  pixel_format: BayerRG8
trigger:
  trigger_type: software

archiving:
  is_archived: "true"
  archive_directory: "save_dir"
  archive_parameters:
    archive_freq: "daily"
    archive_storage: 50 # GB
    archive_days: 30 # days
